version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile  # Đường dẫn tới Dockerfile
    container_name: yii2_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - YII_ENV=dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: yii2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2app
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
